apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: argocdappdemo-ignorediff
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: argocdappdemo-ignorediff
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  namespace: argocdappdemo-ignorediff
data:
  key1: "value1"
  key2: "value2"


